import Container from '@/components/ui/Container';
import Wrapper from '@/components/ui/Wrapper';
import '@/styles/nullstyle.css';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import Footer from '@/components/ui/Footer';

export const metadata: Metadata = {
  title: 'gid.group',
  description: 'Generated by create next app',
  icons: '/Logo.svg'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Container>
          <Wrapper>
            <div id="content">{children}</div>
            <Footer />
          </Wrapper>
        </Container>
      </body>
    </html>
  );
}
